name: Insta AI Post

on:
  schedule:
    # Runs every hour from 9 PM to 1 AM IST (16–19 UTC), all 7 days
    - cron: "0 16-19 * * *"
  workflow_dispatch:       # Keep manual trigger, but no inputs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SMART_API_CLIENT_CODE: ${{ secrets.SMART_API_CLIENT_CODE }}
          SMART_API_KEY: ${{ secrets.SMART_API_KEY }}
          SMART_API_PASSWORD: ${{ secrets.SMART_API_PASSWORD }}
          SMART_API_TOTP: ${{ secrets.SMART_API_TOTP }}
          TELEGRAM_BOT_CHAT_ID: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python post_generator.py
