name: Run Weekly Script

on:
  schedule:
    - cron: "0 6 * * 1"   # Runs every Monday at 6:00 UTC
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Set environment variables
        run: |
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "SMART_API_CLIENT_CODE=${{ secrets.SMART_API_CLIENT_CODE }}" >> $GITHUB_ENV
          echo "SMART_API_KEY=${{ secrets.SMART_API_KEY }}" >> $GITHUB_ENV
          echo "SMART_API_PASSWORD=${{ secrets.SMART_API_PASSWORD }}" >> $GITHUB_ENV
          echo "SMART_API_TOTP=${{ secrets.SMART_API_TOTP }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_CHAT_ID=${{ secrets.TELEGRAM_BOT_CHAT_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
        run: python main.py
